### PR TITLE
Possibly fix `Vec2` rotation arithmetic signs

### PR DESCRIPTION
**Pull request by elfein727**
Deny if I have the wrong idea, but I think this should fix the error I was getting using version 0.6. Do note that 0.6 uses different lines entirely, but the repo seems to have the more correct code.

### CODE REVIEW

**Comment by fu5ha** [comment]
😱 0.6? Latest released version is already 0.9.0 haha

Just looked into this and I think your issue may have been fixed by 9eb7e3779eac13da60429cc6631549b6eb1e0778 already if you really were on 0.6

**Comment by elfein727** [comment]
O:
:O
Well alright then. Not sure what happ.

**Comment by elfein727** [comment]
It's listed as 0.6 in the docs!
image

**Comment by fu5ha** [comment]
Oh noey :( Guess that part of the docs has not been updated with the versions for a bit. PR welcome on that ;D haha

**Pull request closed without merging**
