### PR TITLE
Serde traits for the rest of f64 types

### PR DESCRIPTION
**Pull request by rlidwka**
Exactly the same changes as in https://github.com/fu5ha/ultraviolet/pull/124.

Also fixed currently broken matrix tests, and added tests for Isometry (copy-pasted from existing code above).

~~*Still missing implementation for Similarity.*~~

### CODE REVIEW

**Comment by rlidwka** [comment]
I'm just curious, why aren't all these types derived with existing `serde_derive`?

**Comment by rlidwka** [comment]
Added implementations for all Similarities.

*I don't need them, but it's been bugging me that Isometry has those, but Similarity doesn't.*

**Review by fu5ha — APPROVED** [review]
This all looks quite nice, thank you!

It doesn't use derive for a couple probably not that great reasons

1. I didn't want to require pulling in `serde_derive`.... now, 95% of people use it when they use `serde`, but, I was in a phase of dependency-minimalism and compile-time optimisation when I wrote this crate initially :P
2. The derives obscure the fact that serialization is happening a bit too much, imo. When you write it out you understand exactly what is happening/what you intend to happen more clearly. Whereas with the derives you kinda just slap it on and go, which sometimes can lead to breakages and not fully understanding the contract

**Comment by rlidwka** [comment]
> This all looks quite nice, thank you!

@fu5ha, no problem.

Is there any chance for a new release on `crates.io`? Last one was 6 months ago, and there's been quite a lot of fixes since then.

**Pull request merged**
